---
- name: Fallback
  when: posthooks_rollback and update_successful | default(true) == false
  block:
  - name: Restoring VM to Snapshot taken
    delegate_to: localhost
    community.vmware.vmware_guest_snapshot:
      datacenter: "{{ vcenter_datacenter }}"
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_certifcate_validation }}"
      uuid: "{{ machine }}"
      snapshot_name: "{{ snapshot_name }}"
      state: revert
  - name: Start restored VM
    delegate_to: localhost
    changed_when: snaphot_start.invalid is defined
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_certifcate_validation }}"
      uuid: "{{ machine }}"
      state: poweredon
- name: Removing old Snapshot
  when: posthooks_autoremove
  delegate_to: localhost
  changed_when: snaphot_remove.invalid is defined
  community.vmware.vmware_guest_snapshot:
    datacenter: "{{ vcenter_datacenter }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_certifcate_validation }}"
    uuid: "{{ machine }}"
    snapshot_name: "{{ snapshot_name }}"
    state: absent
- name: Sending E-Mail
  when: mail_enabled
  delegate_to: localhost
  community.general.mail:
    host: "{{ mail.host }}"
    port: "{{ mail.port }}"
    username: "{{ mail.username }}"
    password: "{{ mail.password }}"
    from: "{{ mail.from }}"
    secure: "{{ mail.secure }}"
    to: "{{ mail.to }}"
    subject: "{{ mail_subject }}"
    body: "{{ mail_message }}"
- name: Log lines to MS Teams
  when: webhook_enabled
  delegate_to: localhost
  uri:
    url: "{{ webhook_url }}"
    body: "{{ message }}"
    body_format: json
    method: POST
