---
- name: Fallback
  when: posthooks_rollback and update_successful | default(true) == false
  block:
  - name: Restoring VM to Snapshot taken
    delegate_to: localhost
    vmware_guest_snapshot:
      datacenter: "{{ vcenter_datacenter }}"
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_certifcate_validation }}"
      uuid: "{{ machine[0].uuid }}"
      snapshot_name: "{{ snapshot_name }}"
      state: revert
  - name: Start restored VM
    delegate_to: localhost
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_certifcate_validation }}"
      uuid: "{{ machine[0].uuid }}"
      state: poweredon
- name: Removing old Snapshot
  when: posthooks_autoremove
  delegate_to: localhost
  vmware_guest_snapshot:
    datacenter: "{{ vcenter_datacenter }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_certifcate_validation }}"
    uuid: "{{ machine[0].uuid }}"
    snapshot_name: "{{ snapshot_name }}"
    state: absent
- name: Sending E-Mail (unsuccessful)
  when: mail_enabled and update_successful | default(true) == false
  delegate_to: localhost
  community.general.mail:
    host: "{{ mail.host }}"
    port: "{{ mail.port }}"
    username: "{{ mail.username }}"
    password: "{{ mail.password }}"
    from: "{{ mail.from }}"
    secure: "{{ mail.secure }}"
    to: "{{ mail.to }}"
    subject: "{{ mail_failure_subject }}"
    body: "{{ mail_failure_message }}"
- name: Sending E-Mail (successful)
  when: mail_enabled and update_successful | default(true)
  delegate_to: localhost
  community.general.mail:
    host: "{{ mail.host }}"
    port: "{{ mail.port }}"
    username: "{{ mail.username }}"
    password: "{{ mail.password }}"
    from: "{{ mail.from }}"
    secure: "{{ mail.secure }}"
    to: "{{ mail.to }}"
    subject: "{{ mail_success_subject }}"
    body: "{{ mail_success_message }}"