---
#Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: false
  become: true
  become_method: runas
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        #category_names: ['SecurityUpdates']
      register: result

    # output results
    - debug: var=result

    # reboot only if required
    - win_reboot:
      when: result.reboot_required
