---
#Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
    - name: Update Installation
      until: win_update.found_update_count == 0
      retries: 3
      delay: 10
      block:
      - name: Running Windows Update
        ignore_errors: true
        win_updates:
          category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
          #category_names: ['SecurityUpdates']
        register: win_update

      # output results
      - debug: var=win_update

      # reboot only if required
      - win_reboot:
        when: win_update.reboot_required
