---
- name: Set vSphere uuid 
  set_fact:
    machine: "{{ config.uuid }}"
- name: Show machine uuid
  debug:
    msg: "{{ machine }}"
- name: Remove old VM-Snapshots
  delegate_to: localhost
  changed_when: snaphot_remove.invalid is defined
  community.vmware.vmware_guest_snapshot:
    datacenter: "{{ vcenter_datacenter }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_certifcate_validation }}"
    uuid: "{{ machine }}"
    state: absent
    snapshot_name: "{{ snapshot_name }}"
    description: "{{ snapshot_description }}"
- name: Create new VM-Snapshots
  delegate_to: localhost
  changed_when: snaphot_create.invalid is defined
  community.vmware.vmware_guest_snapshot:
    datacenter: "{{ vcenter_datacenter }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_certifcate_validation }}"
    uuid: "{{ machine }}"
    state: present
    snapshot_name: "{{ snapshot_name }}"
    description: "{{ snapshot_description }}"