---
snapshot_name: AutoSnapshot before Sysupgrade
snapshot_description: This Snapshot is automatically created by Ansible and should only be removed if the playbook failed to autoremove it. 

vcenter_datacenter: "DC01"
vcenter_hostname: "vsphere.local"
vcenter_certifcate_validation: True
vcenter_username: "Administrator@vsphere.local"
vcenter_password: "password"

posthooks_rollback: true
posthooks_autoremove: false


mail_enabled: false
mail_status_error: 
  msg: No status available
mail_subject: |
  {% if update_successful | default(true) == false %}
  Patching of {{ inventory_hostname }} failed
  {% else %}
  Patching of {{ inventory_hostname }} succeded
  {% endif %}
mail_message: "{{ lookup('template', 'mail_message.j2') }}"

mail:
  host: mail.local
  port: 25
  secure: starttls
  username: {}
  password: {}
  from: "ansible@mail.local (Ansible No-Reply)"
  to: User <user@mail.local>


webhook_enabled: false
webhook_status_error: 
  msg: No status available
webhook_url: 'https://outlook.office.com/webhook/your_webhook_url'
message: "{{ lookup('template', 'webhook_message.j2') }}"